version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: crypto_watcher_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: crypto_watcher
      POSTGRES_USER: cryptowatcher_appuser
      POSTGRES_PASSWORD: watcher123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
